const sdata = [
	{
		id: 1,
		imgsrc: "../../src/assets/cta1.png",
		heading: "Launch Fast",
		st1: "Fully responsive e-commerce website & mobile app.",
		st2: "Loads 6X faster than existing solutions.",
		st3: "Upload/import products and inventory in bulk.",
		st4: "Integrate payment gateways.",
		st5: "Easily customizable themes.",
		order1: 1,
		order2: 2,
	},
	{
		id: 2,
		imgsrc: "../../src/assets/cta2.png",
		heading: "Scale Faster",
		st1: "Your store will have 99.5% uptime.",
		st2: "60+ third party plugins.",
		st3: "Marketing tools and discounts to drive repeat orders.",
		st4: "Add staff accounts, assign different roles.",
		st5: "Unlimited transactions, 0% transaction fees.",
		order1: 2,
		order2: 1,
	},
	{
		id: 3,
		imgsrc: "../../src/assets/cta3.png",
		heading: "Manage Better",
		st1: "Order tracking, invoicing and order reports.",
		st2: "Bulk edit product prices, variants, inventory.",
		st3: "Manage global deliveries.",
		st4: "In-depth business analytics.",
		st5: "Automate all tax calculations.",
		order1: 1,
		order2: 2,
	},
];
export default sdata;
